name: test111111
favicon: null
layout_spectrum: 0.2934163808822632
typography_spectrum: 0.7229074006900191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6406429705675691
  lightness: 0.621007647132501
  saturation: 0.7517706269863993
  rhythmicContrast: 0.2667227790225297
purpose: []
